# Debug mode
debug: false
# Storage system (Only mysql is supported for now)
storage:
  type: mysql
  mysql:
    prefix: "host_"
    hostname: "localhost:3306"
    database: "minecraft"
    username: "user"
    password: "pass"
# The type can be "host" for a game server or "lobby" for a lobby server, if you only need the API you can set "none"
server-type: lobby
